spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordertable?useSSL=false
    username: root
    password: zxcvbnm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
server:
  port: 9092